services:
  - type: web
    name: infant-jesus-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: infant-jesus-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: infant-jesus-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: infant-jesus-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: superadmin
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: ADMIN_EMAIL
        value: visithrand@gmail.com
      - key: MAIL_TO
        value: infantjesusdvk@gmail.com

databases:
  - name: infant-jesus-db
    databaseName: infantjesus
    user: infantjesus_user
