services:
  - type: web
    name: infant-jesus-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        value: jdbc:mysql://34.56.9.172:3306/marksly?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&allowMultiQueries=true&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true&useLocalSessionState=true&useLocalTransactionState=true&cacheResultSetMetadata=true&cacheServerConfiguration=true&elideSetAutoCommits=true&maintainTimeStats=false
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: Sri@2004
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: superadmin
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: ADMIN_EMAIL
        value: visithrand@gmail.com
      - key: MAIL_TO
        value: infantjesusdvk@gmail.com
