services:
  - type: web
    name: infant-jesus-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d40uurqli9vc73c03t0g-a.oregon-postgres.render.com:5432/app_db_unkc
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: rcWOBN1Vc32VQVGfaYMSbTWG99phjU8x
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: superadmin
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: ADMIN_EMAIL
        value: visithrand@gmail.com
      - key: MAIL_TO
        value: infantjesusdvk@gmail.com
